#!/bin/bash

# Script to help find the correct IP for accessing from phone
# This must be run on the HOST machine, not in the container

echo "=========================================="
echo "ReciFind - Network Access Helper"
echo "=========================================="
echo ""
echo "⚠️  NOTE: You are currently in a Docker container!"
echo ""
echo "To access ReciFind from your phone:"
echo ""
echo "1. Exit the container (or open a new terminal on your HOST machine)"
echo ""
echo "2. Run one of these commands on your HOST computer:"
echo ""
echo "   On Windows:"
echo "   -----------"
echo "   ipconfig"
echo "   (Look for 'IPv4 Address' under WiFi/Ethernet)"
echo ""
echo "   On Mac/Linux:"
echo "   -------------"
echo "   ifconfig | grep 'inet ' | grep -v 127.0.0.1"
echo "   OR"
echo "   ip addr show | grep 'inet ' | grep -v 127.0.0.1"
echo ""
echo "3. Find the IP that starts with 192.168.x.x or 10.x.x.x"
echo ""
echo "4. On your phone, open:"
echo "   http://<YOUR_HOST_IP>:3000"
echo ""
echo "   Example: http://192.168.1.100:3000"
echo ""
echo "5. Make sure your phone is on the SAME WiFi network!"
echo ""
echo "=========================================="
echo ""
echo "Container info (for reference):"
echo "- Container IP: $(hostname -I | awk '{print $1}')"
echo "- Gateway IP: $(ip route | grep default | awk '{print $3}')"
echo ""
echo "These are Docker internal IPs and won't work from your phone."
echo "=========================================="
